name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 12 */5 * *'  # every 5 days at noon
  workflow_dispatch:

jobs:
  wake_app:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Electricity Forecasting App
        run: |
          curl -L --max-time 60 \
          "https://electricity-demand-forecasting-with-lstm-xgboost-sarima.streamlit.app/" \
          -H "User-Agent: Mozilla/5.0"
          echo "App pinged successfully"

      - name: Wake NYC Delay Dashboard
        run: |
          curl -L --max-time 60 \
          "https://nyc-delay-dashboard.streamlit.app/" \
          -H "User-Agent: Mozilla/5.0"
          echo "NYC Delay Dashboard pinged successfully"
